1. Write a Python program to convert a list of numeric value into a one-dimensional
NumPy array.
Expected Output:
Original List: [12.23, 13.32, 100, 36.32]
One-dimensional numpy array: [ 12.23 13.32 100. 36.32]

In [1]:
import numpy as np

1. Write a Python program to convert a list of numeric value into a one-dimensional
NumPy array.
Expected Output:
Original List: [12.23, 13.32, 100, 36.32]
One-dimensional numpy array: [ 12.23 13.32 100. 36.32]

In [2]:
examplelist = [12.23, 13.32, 100, 36.32]
print("Original list:",examplelist,"type is",type(examplelist))
arr = np.array(examplelist)
print("Array created",arr,"type is",type(arr))


Original list: [12.23, 13.32, 100, 36.32] type is <class 'list'>
Array created [ 12.23  13.32 100.    36.32] type is <class 'numpy.ndarray'>


2. Create a 3x3 matrix with values ranging from 2 to 10.
Expected Output:
[[ 2 3 4]
[ 5 6 7]
[ 8 9 10]]

In [3]:
matrix3x3 = np.arange(1,10).reshape(3,3)
print(matrix3x3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


3. Write a Python program to create a null vector of size 10 and update sixth value to 11.
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [4]:
null_vec = np.zeros(10)
print("Original array:\n",null_vec)
null_vec[6] = 11
print("Updated array:\n",null_vec)

Original array:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Updated array:
 [ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


4. Write a Python program to reverse an array (first element becomes last).
Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [5]:
ori_arr = np.arange(12,38)
print("Original array:\n",ori_arr)
print("Reversed array:\n",np.flip(ori_arr))

Original array:
 [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reversed array:
 [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


5. Write a Python program to create a 2d array with 1 on the border and 0 inside.
Expected Output:

Original array:
[[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]
[ 1. 1. 1. 1. 1.]]

1 on the border and 0 inside in the array
[[ 1. 1. 1. 1. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 0. 0. 0. 1.]
[ 1. 1. 1. 1. 1.]]

In [6]:
arr2d = np.ones((5,5))
print("Original matrix:\n",arr2d)
arr2d = np.zeros((3,3))
print("Updated matrix:\n",np.pad(arr2d, pad_width=1, mode= 'constant', constant_values = 1))

Original matrix:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Updated matrix:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


6. Write a Python program to add a border (filled with 0's) around an existing array.
Expected Output:
Original array:
[[ 1. 1. 1.]
[ 1. 1. 1.]
[ 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 0. 0. 0. 0. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 1. 1. 1. 0.]
[ 0. 0. 0. 0. 0.]]

In [7]:
border0 = np.ones((3,3))
print("Original matrix:\n",border0)
print("Updated matrix:\n",np.pad(border0, pad_width=1, mode='constant', constant_values = 0))

Original matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Updated matrix:
 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.
Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]]

In [8]:
matrix8x8 = np.zeros((8,8))
print("Original matrix:\n",matrix8x8)
for r in range(len(matrix8x8)):
    for c in range(len(matrix8x8)):
        if r%2 == 0 and c%2 != 0:
            matrix8x8[r][c] = 1
        elif r%2 !=0 and c%2 == 0:
            matrix8x8[r][c] = 1


print("Updated matix:\n",matrix8x8)

Original matrix:
 [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
Updated matix:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


8. Write a Python program to convert a list and tuple into arrays.
List to array:
[1 2 3 4 5 6 7 8]
Tuple to array:
[[8 4 6]
[1 2 3]]

In [9]:
lst = [1,2,3,4,5]
tup = (5,6,7,8,9)
lstarr = np.array(lst)
print("List to array: ",lstarr)
tuparr = np.array(tup)
print("Tuple to array: ",tuparr)

List to array:  [1 2 3 4 5]
Tuple to array:  [5 6 7 8 9]


9. Write a Python program to append values to the end of an array.
Expected Output:
Original array:
[10, 20, 30]

After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]

In [10]:
appendarr = np.arange(5)
print("Original array: ",appendarr)
print("Appended array: ",np.append(appendarr, tup))

Original array:  [0 1 2 3 4]
Appended array:  [0 1 2 3 4 5 6 7 8 9]


10. Write a Python program to find the real and imaginary parts of an array of complex
numbers.
Expected Output:
Original array [ 1.00000000+0.j 0.70710678+0.70710678j]
Real part of the array:
[ 1. 0.70710678]
Imaginary part of the array:
[ 0. 0.70710678]

In [12]:
x = np.sqrt([1 + 0j])

y = np.sqrt([0 + 1j])

print("Original array:x ", x)
print("Original array:y ", y)

print("Real part of the array:")
print(x.real)
print(y.real)

print("Imaginary part of the array:")
print(x.imag)
print(y.imag) 

Original array:x  [1.+0.j]
Original array:y  [0.70710678+0.70710678j]
Real part of the array:
[1.]
[0.70710678]
Imaginary part of the array:
[0.]
[0.70710678]


11. Write a Python program to find the number of elements of an array, length of one
array element in bytes and total bytes consumed by the elements.
Expected Output:
Size of the array: 3
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array: 24

In [13]:
lenarr = np.array([1,2,3], dtype=np.float64)
print("Size of one item in bytes: ",lenarr[0].itemsize)
print("Total size of array in bytes: ",(lenarr[0].itemsize)*(lenarr.size))

Size of one item in bytes:  8
Total size of array in bytes:  24


12. Write a Python program to find common values between two arrays.
Expected Output:
Array1: [ 0 10 20 40 60]
Array2: [10, 30, 40]
Common values between two arrays:
[10 40]

In [14]:
arracommon1 = np.array([0,10,20,40,60])
arracommon2 = np.array([10,30,40])
print(f"Common elements between {arracommon1} and {arracommon2} : {np.intersect1d(arracommon1, arracommon2)}")


Common elements between [ 0 10 20 40 60] and [10 30 40] : [10 40]


13. Write a Python program to find the set difference of two arrays. The set difference
will return the sorted, unique values in array1 that are not in array2.
Expected Output:
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70, 90]
Set difference between two arrays:
[ 0 20 60 80]

In [15]:
arraydiff1 = np.array([0,10,20,40,60,80])
arraydiff2 = np.array([10, 30, 40, 50, 70, 90])
print("The original arrays: ",arraydiff1, arraydiff2)
print("The result array: ",np.sort(np.setdiff1d(arraydiff1, arraydiff2)))

The original arrays:  [ 0 10 20 40 60 80] [10 30 40 50 70 90]
The result array:  [ 0 20 60 80]


14. Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or
will return the sorted, unique values that are in only one (not both) of the input arrays.
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]

In [16]:
arrayex1 = np.array( [ 0, 10, 20, 40, 60, 80])
arrayex2 = np.array( [10, 30, 40, 50, 70])

print("The original arrays: ",arrayex1, arrayex2)
print("The result array: ",np.sort(np.setxor1d(arrayex1, arrayex2)))

The original arrays:  [ 0 10 20 40 60 80] [10 30 40 50 70]
The result array:  [ 0 20 30 50 60 70 80]


15. Write a Python program compare two arrays using numpy.
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]

In [18]:
comparr1 = np.array([1,2])
comparr2 = np.array([4,5])
print("array1 > array2")
print(np.greater(comparr1, comparr2))
 
print("array1 >= array2")
print(np.greater_equal(comparr1, comparr2))
 
print("array1 < array2")
print(np.less(comparr1, comparr2))
 
print("array1 <= array2")
print(np.less_equal(comparr1, comparr2))

array1 > array2
[False False]
array1 >= array2
[False False]
array1 < array2
[ True  True]
array1 <= array2
[ True  True]


16. Write a Python program to save a NumPy array to a text file.

In [19]:
arraytxt = np.array([ 0, 10, 20, 40, 60, 80])
np.savetxt("question16.txt",arraytxt,delimiter=',')
print("file saved!")
saved_file = open("question16.txt", 'r')# open file in read mode 
  
print("the file contains:") 
print(saved_file.read()) 

file saved!
the file contains:
0.000000000000000000e+00
1.000000000000000000e+01
2.000000000000000000e+01
4.000000000000000000e+01
6.000000000000000000e+01
8.000000000000000000e+01



17. Write a Python program to create a contiguous flattened array.
Original array:
[[10 20 30]
[20 40 50]]
New flattened array:
[10 20 30 20 40 50]

In [20]:
flatarray = np.array([[1,2,3],[4,5,6]])
print("Original array:\n",flatarray)
print("Flattened array",flatarray.ravel())

Original array:
 [[1 2 3]
 [4 5 6]]
Flattened array [1 2 3 4 5 6]


18. Write a Python program to change the data type of an array.
Expected Output:
[[ 2 4 6]
[ 6 8 10]]
Data type of the array x is: int32
New Type: float64
[[ 2. 4. 6.]
[ 6. 8. 10.]]

In [21]:
arraydata = np.array([[1,2,3],[4,5,6]])
print("The original array\n",arraydata)
print("The updated array\n",arraydata.astype(float))

The original array
 [[1 2 3]
 [4 5 6]]
The updated array
 [[1. 2. 3.]
 [4. 5. 6.]]


19. Write a Python program to create a 3-D array with ones on a diagonal and zeros
elsewhere.
Expected Output:
[[ 1. 0. 0.]
[ 0. 1. 0.]
[ 0. 0. 1.]]

In [22]:
arraydiagone = np.eye(3)
print("Array with diagonal values as one\n",arraydiagone)

Array with diagonal values as one
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


20. Write a Python program to create an array which looks like below array.
Expected Output:
[[ 0. 0. 0.]
[ 1. 0. 0.]
[ 1. 1. 0.]
[ 1. 1. 1.]]

In [23]:
lowertriangular = np.ones((4,3))
print(np.tril(lowertriangular, k=-1))



[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


21. Write a Python program to concatenate two 2-dimensional arrays.
Expected Output:
Sample arrays: ([[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]
Expected Output:
[[ 0 1 3 0 2 4]
[ 5 7 9 6 8 10]]

In [24]:
arracon1 = np.array([[0, 1, 3], [5, 7, 9]])
arracon2 = np.array([[0, 2, 4], [6, 8, 10]])
print("The original arrays\n",arracon1,"\n",arracon2)
print("The result array\n",np.concatenate((arracon1,arracon2), axis=1))


The original arrays
 [[0 1 3]
 [5 7 9]] 
 [[ 0  2  4]
 [ 6  8 10]]
The result array
 [[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


22. Write a Python program to make an array immutable (read-only).
Expected Output:
Test the array is read-only or not:
Try to change the value of the first element:
Traceback (most recent call last):
File "19236bd0-0bd9-11e7-a232-c706d0968eb6.py", line 6, in
x[0] = 1
ValueError: assignment destination is read-only

In [26]:
immut_array = np.zeros(11)
print("Original array ",immut_array)
immut_array[1] = 2
print("Mutated array ",immut_array)
 
immut_array.setflags(write=False)
print("Now the array is immutable")
print("Trying to mutate it")
immut_array[1] = 7

Original array  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Mutated array  [0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Now the array is immutable
Trying to mutate it


ValueError: assignment destination is read-only

23. Write a Python program to create an array of (3, 4) shape, multiply every element
value by 3 and display the new array.
Expected Output:
Original array elements:
[[ 0 1 2 3]
[ 4 5 6 7]
[ 8 9 10 11]]
New array elements:
[[ 0 3 6 9]
[12 15 18 21]
[24 27 30 33]]

In [27]:
array_multi = np.array([[ 0, 1, 2, 3],[ 4, 5, 6, 7],[ 8, 9, 10, 11]])
print("Original array\n",array_multi)
print("Resultant array after mutiplying by 3\n",np.multiply(array_multi,3))

Original array
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Resultant array after mutiplying by 3
 [[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


24. Write a Python program to convert a NumPy array into Python list structure.
Expected Output:
Original array elements:
[[0 1]
[2 3]
[4 5]]
Array to list:
[[0, 1], [2, 3], [4, 5]]

In [28]:
array_to_list = np.array([[0, 1],[2, 3],[4, 5]])
print(f"The original array \n{array_to_list}.\nits type {type(array_to_list)}")

array_list = array_to_list.tolist()
print(f"The list created \n{array_list}.\nits type {type(array_list)}")

The original array 
[[0 1]
 [2 3]
 [4 5]].
its type <class 'numpy.ndarray'>
The list created 
[[0, 1], [2, 3], [4, 5]].
its type <class 'list'>


25. Write a Python program to convert a NumPy array into Python list structure.
Expected Output:

Original array elements:[ 0.26153123 0.52760141 0.5718299 0.5927067 0.7831874 0.69746349
0.35399976 0.99469633 0.0694458 0.54711478]

Print array values with precision 3:
[ 0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]

In [29]:
precision3 = np.array([ 0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874, 0.69746349,
0.35399976, 0.99469633, 0.0694458, 0.54711478])
np.set_printoptions(precision = 3, suppress = True)
print("Arry values with precision 3",precision3)


Arry values with precision 3 [0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]


26. Write a Python program to suppresses the use of scientific notation for small
numbers in numpy array.
Expected Output:
Original array elements:
[ 1.60000000e-10 1.60000000e+00 1.20000000e+03 2.35000000e-01]
Print array values with precision 3:
[ 0. 1.6 1200. 0.235]

In [31]:
array26 = np.array([ 1.60000000e-10, 1.60000000e+00, 1.20000000e+03, 2.35000000e-01])
print("Array values with precision 3 ",array26)

Array values with precision 3  [   0.       1.6   1200.       0.235]


27. Write a Python program to how to add an extra column to an numpy array.
Expected Output:
[[ 10 20 30 100]
[ 40 50 60 200]]

In [2]:
array27 = np.array([[ 10, 20, 30],[ 40, 50, 60,]])
print("The origin array\n",array27)
new_array27 = np.append(array27, [[100],[200]], axis =1)
print("After adding column\n",new_array27)

The origin array
 [[10 20 30]
 [40 50 60]]
After adding column
 [[ 10  20  30 100]
 [ 40  50  60 200]]
